### ISSUE TITLE
TypeError: 'set' on proxy: trap returned falsish for property 'modules' for ModuleConcatenationPlugin

### ISSUE THREAD

**Issue by rnaud** [stephencookdev/speed-measure-webpack-plugin#12]
Hello again :)
Here is another issue I encountered when running this plugin using `ModuleConcatenationPlugin`

Full stacktrace:

```
/Users/anf/projects/my_app/node_modules/webpack/lib/optimize/ModuleConcatenationPlugin.js:181
        compilation.modules = compilation.modules.filter(m => !usedModules.has(m));
                            ^

TypeError: 'set' on proxy: trap returned falsish for property 'modules'
  at Proxy.compilation.plugin (/Users/anf/projects/my_app/node_modules/webpack/lib/optimize/ModuleConcatenationPlugin.js:181:25)
  at Compilation.wrappedFunc (/Users/anf/projects/my_app/node_modules/speed-measure-webpack-plugin/WrappedPlugin/index.js:13:24)
  at Compilation.applyPluginsBailResult (/Users/anf/projects/my_app/node_modules/tapable/lib/Tapable.js:129:27)
  at sealPart2 (/Users/anf/projects/my_app/node_modules/webpack/lib/Compilation.js:613:10)
  at Compilation.applyPluginsAsyncSeries (/Users/anf/projects/my_app/node_modules/tapable/lib/Tapable.js:195:46)
  at Compilation.seal (/Users/anf/projects/my_app/node_modules/webpack/lib/Compilation.js:605:8)
  at applyPluginsParallel.err (/Users/anf/projects/my_app/node_modules/webpack/lib/Compiler.js:504:17)
  at /Users/anf/projects/my_app/node_modules/tapable/lib/Tapable.js:289:11
  at _addModuleChain (/Users/anf/projects/my_app/node_modules/webpack/lib/Compilation.js:507:11)
  at processModuleDependencies.err (/Users/anf/projects/my_app/node_modules/webpack/lib/Compilation.js:477:14)
  at process._tickCallback (internal/process/next_tick.js:150:11)
```

**Comment by stephencookdev** [comment]
Thanks for raising :)

I'm fairly sure this is the same issue as https://github.com/stephencookdev/speed-measure-webpack-plugin/issues/10 but will check tomorrow morning

**Comment by stephencookdev** [comment]
So this should have fixed the issue: https://github.com/stephencookdev/speed-measure-webpack-plugin/pull/13

Let me know :)

**Comment by rnaud** [comment]
I can confirm this is fixed, thank you for the very fast turn around!
