### ISSUE TITLE
TypeError: Cannot read property 'PROCESS_ASSETS_STAGE_ADDITIONS' of undefined when using speed-measure-webpack-plugin

### ISSUE THREAD

**Issue by ceisele-r** [stephencookdev/speed-measure-webpack-plugin#155]
As soon as I add the `smp.wrap(..)` around my webpack config, I am getting the following exception:
```
(node:29480) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
[webpack-cli] TypeError: Cannot read property 'PROCESS_ASSETS_STAGE_ADDITIONS' of undefined
    at Proxy.<anonymous> (C:\proj\app\node_modules\copy-webpack-plugin\dist\index.js:462:45)
    at C:\proj\app\node_modules\speed-measure-webpack-plugin\WrappedPlugin\index.js:52:19
    at Hook.eval [as call] (eval at create (C:\proj\app\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:5:1)
    at Hook.CALL_DELEGATE [as _call] (C:\proj\app\node_modules\tapable\lib\Hook.js:14:14)
    at Compiler.newCompilation (C:\proj\app\node_modules\webpack\lib\Compiler.js:990:30)
    at C:\proj\app\node_modules\webpack\lib\Compiler.js:1033:29
    at eval (eval at create (C:\proj\app\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at C:\proj\app\node_modules\speed-measure-webpack-plugin\WrappedPlugin\index.js:44:9
    at Proxy.<anonymous> (C:\proj\app\node_modules\webpack\lib\DllReferencePlugin.js:80:12)
    at C:\proj\app\node_modules\speed-measure-webpack-plugin\WrappedPlugin\index.js:40:16
```

As you can see, we are using the copy-webpack-plugin.
Without the `smp.wrap(...)`, everything works as expected.

The environment is:

- node v12.19.0
- webpack 5.16.0
- copy-webpack-plugin 7.0.0
- webpack-cli 4.4.0

**Comment by takhello** [comment]
same situation

**Comment by takhello** [comment]
[webpack-cli] TypeError: Cannot read property 'PROCESS_ASSETS_STAGE_ADDITIONS' of undefined

**Comment by ceisele-r** [comment]
Relates to https://github.com/stephencookdev/speed-measure-webpack-plugin/issues/149

**Comment by caseyjhol** [comment]
Getting the same error with:
- node v14.10.0
- webpack v5.18.0
- webpack-cli v4.4.0

**Comment by marcobouwmeester** [comment]
I am having the same issue. It seems to be caused by copy-webpack-plugin v7.0.0 . Downgrading back to v6.0.4 seems to resolve the error for now.

**Comment by Kocal** [comment]
I have the same issue with favicons-webpack-plugin at version ^5.0.0-alpha.11

**Comment by zhangzippo** [comment]
i have the same  issue too

**Comment by stephencookdev** [comment]
Hey @ceisele-r — I have recently made the move to launch [18ways.com](https://18ways.com) (AI-first, keyless i18n infra), and more generally try to make a living out of making devs lives' less awful.

As such, SMP has now been bumped to [v1.6](https://github.com/stephencookdev/speed-measure-webpack-plugin/releases/tag/v1.6.0), adding Webpack 5 support, and I'm going to be engaging more closely with issues over the next few weeks!
