### ISSUE TITLE
Unexpected token '...' from chalk module using SMP 1.5.0

### ISSUE THREAD

**Issue by gengengengengen** [stephencookdev/speed-measure-webpack-plugin#204]
Hello, i am working at a old project which based on
node v6.10.0
npm v3.10.10
webpack 1.15
and I need to using SMP for the project. After install the SMP 1.5.0, I met the error of Unexpected token '...' from chalk module imported by SMP. It seemed like the smp modules was not be compiled before running?

```
[my project path]/node_modules/speed-measure-webpack-plugin/node_modules/chalk/source/index.js:106
	...styles,
	^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ([my project path]/node_modules/speed-measure-webpack-plugin/index.js:3:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

I tried higher node/npm in local developing and SMP 1.5.0 works fine. But for some reason i cannot update higher versions of node/npm/webpack in the CI pipeline of production environment.

I also tried downgrade the SMP to 0.3.0, error message turned to TypeError: smp.wrap is not a function.

The webpack config is wrote like:

```
  const SMP = require("speed-measure-webpack-plugin");
  const smp = new SMP({
    disable: false, 
    outputFormat: "humanVerbose",
    loaderTopFiles: 100,
  });
  const wrappedConfig = smp.wrap(
    webpackConfig
  );

```
Is there any right config way for old prject? Thank you very much.

**Comment by gengengengengen** [comment]
SMP runs fine using version 1.3.3
