### ISSUE TITLE
Worker error Error: No code sections found

### ISSUE THREAD

**Issue by SirWindfield** [stephencookdev/speed-measure-webpack-plugin#40]
at Bundle.validate (/home/sven/projects/devRantron/node_modules/inspectpack/lib/models/bundle.js:54:11)
    at createBundle (/home/sven/projects/devRantron/node_modules/inspectpack/lib/models/bundle.js:262:12)
    at Immediate.setImmediate (/home/sven/projects/devRantron/node_modules/inspectpack/lib/models/bundle.js:313:7)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)

I get this output around 7-10 times each build. 

webpack: 4.5.0
webpack-cli: 2.0.14
plugin: 1.2.2

**Comment by stephencookdev** [comment]
Hey - just trying to work out the error

I'm a little confused. Looking at [inspectpack](https://github.com/FormidableLabs/inspectpack) it seems it runs on the generated bundle. I don't get how it would be interacting with SMP at all?

Can you share a tiny bit of your set-up?

**Comment by SirWindfield** [comment]
Looks like it triggers in combination with the DashboardPlugin. I didn't notice that it isn't webpack 4 capable. Sorry to have bothered you.
After removing the DashboardPlugin everything works fine!
