### ISSUE TITLE
Cannot read property 'tap' of undefined

### ISSUE THREAD

**Issue by liuzhiyang0113** [stephencookdev/speed-measure-webpack-plugin#50]
i use create-react-app , but i upgrade webpack4 .19.0.

it throw error.

> demo1@0.1.0 start /Users/mac/Desktop/study/webpack-study/demo1
> node scripts/start.js

Cannot read property 'tap' of undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! demo1@0.1.0 start: `node scripts/start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the demo1@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2018-09-22T08_11_44_724Z-debug.log

>>> /Users/mac/.npm/_logs/2018-09-22T08_11_44_724Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle demo1@0.1.0~prestart: demo1@0.1.0
6 info lifecycle demo1@0.1.0~start: demo1@0.1.0
7 verbose lifecycle demo1@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle demo1@0.1.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/mac/Desktop/study/webpack-study/demo1/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle demo1@0.1.0~start: CWD: /Users/mac/Desktop/study/webpack-study/demo1
10 silly lifecycle demo1@0.1.0~start: Args: [ '-c', 'node scripts/start.js' ]
11 silly lifecycle demo1@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle demo1@0.1.0~start: Failed to exec start script
13 verbose stack Error: demo1@0.1.0 start: `node scripts/start.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid demo1@0.1.0
15 verbose cwd /Users/mac/Desktop/study/webpack-study/demo1
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error demo1@0.1.0 start: `node scripts/start.js`
22 error Exit status 1
23 error Failed at the demo1@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by jclarkpatientping** [comment]
I see this with anything above 4.18.1 of webpack.

**Comment by stephencookdev** [comment]
So we actually have some integration tests for webpack 4, which are currently locked to 4.19.1, and are working fine.

I've just run the tests with 4.18.1 and 4.20.2 (the most recent version at the time of writing) - and the tests seem to pass.

Does this issue occur on the initial build, or on incremental builds (i.e. in watch mode, after the initial build, after a file is saved)?

If it's an initial build, it would be great if you guys could edit one of the integration tests to reproduce the issue? I think it might be a specific plugin that's causing the issue...

**Comment by jerryOnlyZRJ** [comment]
> So we actually have some integration tests for webpack 4, which are currently locked to 4.19.1, and are working fine.
> 
> I've just run the tests with 4.18.1 and 4.20.2 (the most recent version at the time of writing) - and the tests seem to pass.
> 
> Does this issue occur on the initial build, or on incremental builds (i.e. in watch mode, after the initial build, after a file is saved)?
> 
> If it's an initial build, it would be great if you guys could edit one of the integration tests to reproduce the issue? I think it might be a specific plugin that's causing the issue...

It can't work with html-webpack-plugin hooks like html-webpack-plugin-before-html-processing, when we tap these events, the error occurred.

**Comment by cypherix93** [comment]
This is most definitely still an issue. `html-webpack-plugin` seems to be the culprit here.

```
compilation.hooks.htmlWebpackPluginBeforeHtmlProcessing.tap(... 
                                                        ^
TypeError: Cannot read property 'tap' of undefined
```
