### ISSUE TITLE
Breaks with HtmlWebpackHarddiskPlugin & BaseHrefWebpackPlugin

### ISSUE THREAD

**Issue by mkaradeniz** [stephencookdev/speed-measure-webpack-plugin#55]
Hey!

Thanks for this project :)

I ran into issues that are maybe related to #44:
When including `HtmlWebpackHarddiskPlugin` and/or `BaseHrefWebpackPlugin`

**Comment by sibelius** [comment]
it breaks with favicons-webpack-plugin as well

```
10% building modules 1/1 modules 0 activeTypeError: Cannot read property 'tapAsync' of undefined
    at Proxy.<anonymous> (/Users/sibelius/Dev/app/app/app-admin/node_modules/favicons-webpack-plugin/index.js:73:62)
    at args (/Users/sibelius/Dev/app/app/app-admin/node_modules/speed-measure-webpack-plugin/WrappedPlugin/index.js:52:19)
    at SyncHook.eval [as call] (eval at create (/Users/sibelius/Dev/app/app/app-admin/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:97:1)
    at SyncHook.lazyCompileHook (/Users/sibelius/Dev/app/app/app-admin/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/sibelius/Dev/app/app/app-admin/node_modules/webpack/lib/Compiler.js:503:26)
    at hooks.beforeCompile.callAsync.err (/Users/sibelius/Dev/app/app/app-admin/node_modules/webpack/lib/Compiler.js:539:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/sibelius/Dev/app/app/app-admin/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/sibelius/Dev/app/app/app-admin/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/sibelius/Dev/app/app/app-admin/node_modules/webpack/lib/Compiler.js:534:28)
    at Compiler.runAsChild (/Users/sibelius/Dev/app/app/app-admin/node_modules/webpack/lib/Compiler.js:281:8)
    at /Users/sibelius/Dev/app/app/app-admin/node_modules/favicons-webpack-plugin/lib/compiler.js:75:19
    at new Promise (<anonymous>)
    at Object.compileTemplate (/Users/sibelius/Dev/app/app/app-admin/node_modules/favicons-webpack-plugin/lib/compiler.js:74:10)
    at Proxy.<anonymous> (/Users/sibelius/Dev/app/app/app-admin/node_modules/favicons-webpack-plugin/index.js:48:19)
    at args (/Users/sibelius/Dev/app/app/app-admin/node_modules/speed-measure-webpack-plugin/WrappedPlugin/index.js:40:16)
    at AsyncParallelHook.eval [as callAsync] (eval at create (/Users/sibelius/Dev/app/app/app-admin/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:13:1)
    at AsyncParallelHook.lazyCompileHook (/Users/sibelius/Dev/app/app/app-admin/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.beforeCompile.callAsync.err (/Users/sibelius/Dev/app/app/app-admin/node_modules/webpack/lib/Compiler.js:541:20)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/sibelius/Dev/app/app/app-admin/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/sibelius/Dev/app/app/app-admin/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/sibelius/Dev/app/app/app-admin/node_modules/webpack/lib/Compiler.js:534:28)
    at compiler.hooks.watchRun.callAsync.err (/Users/sibelius/Dev/app/app/app-admin/node_modules/webpack/lib/Watching.js:76:18)
    at _err2 (eval at create (/Users/sibelius/Dev/app/app/app-admin/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:32:1)
    at func.apply.argsButLast.map.concat.callbackArgs (/Users/sibelius/Dev/app/app/app-admin/node_modules/speed-measure-webpack-plugin/WrappedPlugin/index.js:44:9)
    at /Users/sibelius/Dev/app/app/app-admin/node_modules/happypack/node_modules/async/lib/async.js:721:13
    at /Users/sibelius/Dev/app/app/app-admin/node_modules/happypack/node_modules/async/lib/async.js:52:16
    at /Users/sibelius/Dev/app/app/app-admin/node_modules/happypack/node_modules/async/lib/async.js:269:32
    at /Users/sibelius/Dev/app/app/app-admin/node_modules/happypack/node_modules/async/lib/async.js:44:16
    at /Users/sibelius/Dev/app/app/app-admin/node_modules/happypack/node_modules/async/lib/async.js:718:17
    at /Users/sibelius/Dev/app/app/app-admin/node_modules/happypack/node_modules/async/lib/async.js:167:37
```

**Comment by stephencookdev** [comment]
Hey guys - thanks for raising. I'll do my best to take a look at these plugins when I get a mo.

Is it on a regular build that you hit the error, or on an incremental build?

**Comment by sibelius** [comment]
regular one

**Comment by mkaradeniz** [comment]
Thanks!

Yes, regular too.

**Comment by alxpsr** [comment]
same problem

**Comment by shudery** [comment]
same problem

**Comment by X-Jagger** [comment]
broken with html-webpack-include-assets-plugin too.

**Comment by alireza-mh** [comment]
update my package to the latest and now it works.
`html-webpack-plugin: 4.5.0`
