### ISSUE TITLE
issue with fork ts plugin

### ISSUE THREAD

**Issue by MrFrankel** [stephencookdev/speed-measure-webpack-plugin#56]
Message:
    Error: TypeError: Cannot read property 'tap' of undefined
Stack:
Error: Error: TypeError: Cannot read property 'tap' of undefined
    at ForkTsCheckerNotifierWebpackPlugin.apply (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/fork-ts-checker-notifier-webpack-plugin/index.js:65:23)
    at WrappedPlugin.apply (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/speed-measure-webpack-plugin/WrappedPlugin/index.js:277:29)
    at webpack (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/webpack/lib/webpack.js:47:13)
    at Gulp.<anonymous> (/Users/mfrankel/Workspace/amplify-dashboard/webapp/build/gulp/serve.gulp.js:43:22)
    at module.exports (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/run-sequence/index.js:86:16)
    at Gulp.onTaskEnd (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/run-sequence/index.js:75:5)
    at emitOne (events.js:120:20)
    at Gulp.emit (events.js:210:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/orchestrator/index.js:264:8)
    at /Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/end-of-stream/node_modules/once/once.js:17:25)
    at DestroyableTransform.onend (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/end-of-stream/index.js:31:18)
    at emitNone (events.js:110:20)
    at DestroyableTransform.emit (events.js:207:7)
    at /Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)

package.json  

"devDependencies": {
    "@types/angular": "^1.6.10",
    "@types/angular-animate": "^1.5.6",
    "@types/angular-cookies": "^1.4.3",
    "@types/angular-mocks": "^1.5.9",
    "@types/angular-sanitize": "^1.3.4",
    "@types/angular-scroll": "0.0.30",
    "@types/angular-storage": "0.0.30",
    "@types/highcharts": "4.2.52",
    "@types/jasmine": "^2.5.54",
    "@types/jquery": "^2.0.41",
    "@types/lodash": "^3.10.1",
    "@types/mysql": "0.0.31",
    "@types/ng-dialog": "^0.6.0",
    "@types/ng-file-upload": "^12.2.0",
    "@types/node": "^7.0.10",
    "@types/papaparse": "^4.1.28",
    "@types/q": "^1.0.0",
    "@types/selenium-webdriver": "^3.0.0",
    "angular2-template-loader": "^0.6.2",
    "chalk": "^1.1.3",
    "config": "^1.19.0",
    "css-loader": "^0.28.11",
    "file-loader": "^1.1.11",
    "fork-ts-checker-notifier-webpack-plugin": "^0.6.2",
    "fork-ts-checker-webpack-plugin": "^0.4.14",
    "gulp": "^3.9.1",
    "gulp-clean": "^0.3.2",
    "gulp-concat": "^2.6.0",
    "gulp-help": "^1.6.0",
    "gulp-iconfont": "^9.0.0",
    "gulp-insert": "^0.5.0",
    "gulp-protractor": "^4.1.0",
    "gulp-rename": "^1.2.2",
    "gulp-replace": "^0.5.4",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-template": "^3.0.0",
    "gulp-typescript": "^3.1.3",
    "gulp-uncache": "^0.4.0-beta1",
    "gulp-util": "^3.0.8",
    "gulp-webserver": "^0.9.1",
    "gulp-zip": "^3.0.2",
    "happypack": "^5.0.0",
    "hard-source-webpack-plugin": "^0.12.0",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^3.2.0",
    "http-proxy": "^1.14.0",
    "jasmine-reporters": "^2.3.0",
    "jasmine-spec-reporter": "^4.2.1",
    "jshint": "^2.9.5",
    "jshint-stylish": "^2.0.1",
    "karma": "^1.2.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "^1.1.2",
    "karma-junit-reporter": "^1.2.0",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-spec-reporter": "^0.0.32",
    "karma-webpack": "^3.0.0",
    "leonardojs": "^4.0.5",
    "less": "^2.7.2",
    "less-loader": "^4.1.0",
    "lodash.assign": "^3.2.0",
    "merge-stream": "^0.1.8",
    "mkdirp": "^0.5.1",
    "mysql": "^2.10.2",
    "node-proxy-table": "0.0.6",
    "open-browser-webpack-plugin": "^0.0.5",
    "progress-bar-webpack-plugin": "^1.11.0",
    "protractor": "^5.4.1",
    "protractor-jasmine2-screenshot-reporter": "^0.3.3",
    "protractor-retry": "git+https://github.com/MrFrankel/protractor-retry.git",
    "protractor-video-reporter": "^0.3.0",
    "pug": "^2.0.3",
    "pug-loader": "^2.4.0",
    "raw-loader": "^0.5.1",
    "readable-stream": "^2.3.6",
    "request": "^2.69.0",
    "request-promise": "^2.0.1",
    "require-dir": "^0.3.0",
    "run-sequence": "^1.1.1",
    "script-loader": "^0.7.2",
    "share-loader": "^0.2.2",
    "source-map-loader": "^0.2.3",
    "speed-measure-webpack-plugin": "^1.2.3",
    "style-loader": "^0.21.0",
    "svgo": "^1.0.5",
    "svgo-loader": "^2.1.0",
    "ts-loader": "^5.3.0",
    "tslint": "^5.5.0",
    "typescript": "2.8.3",
    "url-loader": "^1.0.1",
    "webpack": "^4.25.0",
    "webpack-bundle-analyzer": "^2.3.1",
    "webpack-cli": "^3.1.2",
    "webpack-dev-middleware": "^3.1.3",
    "webpack-dev-server": "^3.1.10",
    "webpack-visualizer-plugin": "^0.1.11",
    "yargs": "^3.15.0",
    "svg-sprite-loader": "^3.8.0",
    "jasmine": "^3.1.0",
    "jasmine-core": "^3.1.0",
    "optimize-css-assets-webpack-plugin": "3.2.0",
    "mini-css-extract-plugin": "^0.4.0"
  },

help is appreciated, thanks!

**Comment by MrFrankel** [comment]
also

Message:
    Cannot read property 'tap' of undefined
Stack:
TypeError: Cannot read property 'tap' of undefined
    at Proxy.compilerHooks.afterPlugins.tap (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/hard-source-webpack-plugin/lib/ExcludeModulePlugin.js:40:49)
    at args (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/speed-measure-webpack-plugin/WrappedPlugin/index.js:52:19)
    at args (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/webpack/lib/debug/ProfilingPlugin.js:414:10)
    at SyncHook.eval [as call] (eval at create (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:11:1)
    at SyncHook.lazyCompileHook (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/tapable/lib/Hook.js:154:20)
    at WebpackOptionsApply.process (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/webpack/lib/WebpackOptionsApply.js:492:31)
    at webpack (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/webpack/lib/webpack.js:53:48)
    at Gulp.<anonymous> (/Users/mfrankel/Workspace/amplify-dashboard/webapp/build/gulp/serve.gulp.js:43:22)
    at module.exports (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/run-sequence/index.js:86:16)
    at Gulp.onTaskEnd (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/run-sequence/index.js:75:5)
    at emitOne (events.js:120:20)
    at Gulp.emit (events.js:210:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/orchestrator/index.js:264:8)
    at /Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/end-of-stream/node_modules/once/once.js:17:25)
    at DestroyableTransform.onend (/Users/mfrankel/Workspace/amplify-dashboard/webapp/node_modules/end-of-stream/index.js:31:18)

**Comment by stephencookdev** [comment]
Okay, [this package](https://www.npmjs.com/package/fork-ts-checker-notifier-webpack-plugin) is causing the issue, right?

I'll try to take a look as soon as I get a chance

**Comment by ypresto** [comment]
I got this error today:
`TypeError: Cannot read property 'callAsync' of undefined` with webpack watch
https://github.com/Realytics/fork-ts-checker-webpack-plugin/issues/170

webpack: 4.12.0
speed-measure-webpack-plugin: 1.2.3
fork-ts-checker-webpack-plugin: 0.5.0

**Comment by starsolaris** [comment]
Is there any progress with this issue?
