### ISSUE TITLE
TypeError: Cannot read property 'tap' of undefined

### ISSUE THREAD

**Issue by jerryOnlyZRJ** [stephencookdev/speed-measure-webpack-plugin#63]
It seems that can't work with webpack customed hooks such as html-webpack-plugin-before-html-processing in html-webpack-plugin, when we tap these events, the error occurred.
```
compilation.hooks.htmlWebpackPluginBeforeHtmlProcessing.tap(... 
                                                        ^
TypeError: Cannot read property 'tap' of undefined
```

**Comment by liuzhiyang0113** [comment]
i have the same problem

**Comment by stephencookdev** [comment]
Cheers for raising :slightly_smiling_face: 

I'm struggling to repro this a bit. I gather it's from plugins that work _with_ the html-webpack-plugin, rather than that plugin working by itself

I've pushed a branch repro/html-webpack-plugin that includes a webpack config using html-webpack-plugin. You can see at the moment on that branch if you run `npm run prepare ; npm run test ; npm run cleanup` from within the directory `__tests__/setups/v4-html-webpack-plugin` that the tests all pass.

Could you modify that branch to reproduce the issue you're talking about?

**Comment by kazusa0106** [comment]
same proplem 
1.create the project by vue/cli
2.add the webpack config file:
![image](https://user-images.githubusercontent.com/20415057/50477257-80e3b900-0a06-11e9-88cc-5a95c1561434.png)

3.result:
![image](https://user-images.githubusercontent.com/20415057/50477277-a244a500-0a06-11e9-99ae-2cb21fd2d7f3.png)



vue/cli@3.2.1
speed-measure-webpack-plugin@1.2.5

**Comment by jerryOnlyZRJ** [comment]
> Cheers for raising 🙂
> 
> I'm struggling to repro this a bit. I gather it's from plugins that work _with_ the html-webpack-plugin, rather than that plugin working by itself
> 
> I've pushed a branch [repro/html-webpack-plugin](https://github.com/stephencookdev/speed-measure-webpack-plugin/tree/repro/html-webpack-plugin) that includes a webpack config using html-webpack-plugin. You can see at the moment on that branch if you run `npm run prepare ; npm run test ; npm run cleanup` from within the directory `__tests__/setups/v4-html-webpack-plugin` that the tests all pass.
> 
> Could you modify that branch to reproduce the issue you're talking about?

Sure.There is my PR: https://github.com/stephencookdev/speed-measure-webpack-plugin/pull/69

**Comment by kkkman22** [comment]
i have the same problem
![_20190215154719](https://user-images.githubusercontent.com/23480907/52842105-0814f980-3139-11e9-972c-89ae113adb8c.png)

"speed-measure-webpack-plugin": "^1.3.0",
"webpack": "4.29.3",
"webpack-bundle-analyzer": "3.0.3",
"webpack-cli": "3.2.1",
"webpack-dev-server": "3.1.14",
"webpack-merge": "4.2.1"

**Comment by Shubham-Sharma-23** [comment]
Facing the same issue, anyone any luck?

**Comment by huixisheng** [comment]
I have the some problem. create by vue/cli.

vue.config.js
```
module.exports = {
  chainWebpack: (config) => {
     smp.wrap(config);
  }
}
```


```
  /node_modules/@vue/preload-webpack-plugin/src/index.js:114
        compilation.hooks.htmlWebpackPluginBeforeHtmlProcessing.tap(
                                                                ^

TypeError: Cannot read property 'tap' of undefined
    at Proxy.compiler.hooks.compilation.tap.compilation (/node_modules/@vue/preload-webpack-plugin/src/index.js:114:65)
    at args (/node_modules/speed-measure-webpack-plugin/WrappedPlugin/index.js:52:19)
    at SyncHook.eval [as call] (eval at create (/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:17:1)
    at SyncHook.lazyCompileHook (/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/node_modules/webpack/lib/Compiler.js:507:26)
    at hooks.beforeCompile.callAsync.err (/node_modules/webpack/lib/Compiler.js:543:29)
    at _err1 (eval at create (/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:16:1)
    at func.apply.argsButLast.map.concat.callbackArgs (/node_modules/speed-measure-webpack-plugin/WrappedPlugin/index.js:44:9)
    at Array.compiler.inputFileSystem.readFile (/node_modules/webpack/lib/DllReferencePlugin.js:72:15)
    at Storage.finished (/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

**Comment by fizal619** [comment]
I also have the same issue. Will be watching this thread :)

**Comment by vuchan** [comment]
anyone fixed that here?

**Comment by jerryOnlyZRJ** [comment]
> anyone fixed this problem here? solution and why?

Nobody. Because this plugin use the ES6 Proxy to watch all of the compile & compilation's hooks, but when we tap a customed hook, it'll not be proxy.

**Comment by geekox86** [comment]
@jerryOnlyZRJ is there a better approach like proxying the Webpack hooks object for any additions?

**Comment by tstackhouse** [comment]
I've been doing some testing and I found that in the `wrapHooks` function in `WrappedPlugin`, if we change this:

```
  const wrapped = Object.keys(hooks).reduce((acc, method) => {
    acc[method] = genProxy(method);
    return acc;
  }, {});
```

to this:

```  const wrapped = Object.keys(hooks).reduce((acc, method) => {
    acc[method] = genProxy(method);
    return acc;
  }, orig.hooks);
```

The test cases in #69 pass, however it does result in a few errors from SMP, like so:

```
  console.error ../../../index.js:105                                                                                                                                                                                                                             Could not find a matching event to end plugins CustomPlugin/Compiler/done { id: 705 }
```

But that definitely represents a step in the right direction.  It means we might be able to set us a custom proxy object that can handle custom hooks.

**Comment by vpiskunov** [comment]
Any luck with this? Using Vue + Nativescript project, it runs fine when building for ios/native, but fails with the above error on web-build, presuming as html plugin is not used in native builds, but fails as above on web.

**Comment by ryu-wish** [comment]
![image](https://user-images.githubusercontent.com/90606209/134449211-47fc6554-ebe8-4da9-afee-e4ff5b326598.png)
Is there any solution?

**Comment by ankitseepossible** [comment]
I am also facing the same issue while implementing critical css with magento pwa studio.
```
compilation.hooks.htmlWebpackPluginBeforeHtmlProcessing.tap(
                    this.name,
                    ({ plugin: { options } }) => {
                        options.minify = options.minify || {};
                        options.minify.minifyCSS = true;
                    }
                );
```
in above code I am getting `TypeError: Cannot read property 'tap' of undefined`
any solution ?
